from langchain.agents import create_agent
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from tools import web_search, scrape_url  ## import the tools we defined in tools.py
import os
from dotenv import load_dotenv
load_dotenv()

##MODEL SETUP
llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)

## 1st agent :- search_agent for the searching the web using the web_search tool
def build_search_agent():
    return create_agent(
        model=llm,
        tools=[web_search]
    )

## 2nd agent :- reader_agent for scraping the content of a webpage using the scrape_url tool
def build_reader_agent():
    return create_agent(
        model=llm,
        tools=[scrape_url]
    )

##3rd : writer chain takes all the research &write a full report (llm|prompt|stroutput_parser)
writer_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant that writes detailed reports based on the research provided."),
    ("human", """Based on the following research, write a detailed report on the topic below.
     
topic: {topic}
Research_gathered: {research}

Structured the report as follows:
1. Introduction
2. Main Content / key findings (minimum 3 key findings in well explained manner)
3. Conclusion
4. Sources (list all the sources URLs used in the research)

be detailded,factual and professional.""")
])

# we can create a chain for the writer agent by combining the prompt, llm and output parser for better structuring and formatting of the final report.
# The output parser will ensure that the output is in a clean string format.

writer_chain = writer_prompt | llm | StrOutputParser()


##critic_chain is responsible for evaluating the quality of the final report generated by the writer agent. 
# It will provide feedback on the report's content, structure, and overall quality, helping to ensure that the final output is accurate, well-organized, and meets the desired standards.
critic_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a critical evaluator that assesses the quality of reports based on the research provided."),
    ("human", """Evaluate the following report based on the research provided. Provide feedback on the report's content, structure, and overall quality. Highlight any areas that could be improved or are particularly well done.
     report: {report}

     responses should be structured as follows:
     1. Score: (a score out of 10 evaluating the overall quality of the report)
     2. Content Evaluation: Assess the accuracy and relevance of the information presented in the report.
     3. Structure Evaluation: Evaluate the organization and flow of the report, including the clarity of the introduction, main content, and conclusion.
     4. Overall Quality: Provide an overall assessment of the report's quality, including any strengths and weaknesses.
     5. Suggestions for Improvement: Offer specific suggestions for how the report could be improved, if necessary. be detailed, constructive and professional.""")
])
critic_chain = critic_prompt | llm | StrOutputParser()

